### ISSUE TITLE
unexpected operator error

### ISSUE THREAD

**Issue by MarioVilas** [inquam/svn-rename-author#1]
Just tried it out on Ubuntu and got this error:

./svn-rename-author: 14: [: Y: unexpected operator

When replying to the confirmation question. I worked around the issue by eliminating the question entirely.

**Comment by graue70** [comment]
The problem is that the == (double equals) operator is bash dependent and might not work without it. My pull request should fix this.
If you run the original script with sh the mentioned errors appear.
